- app/assets/stylesheets/application.scss
- app/assets/stylesheets/content_header.scss
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/shared/_mixin.scss
- app/assets/stylesheets/shared/_variables.scss
- app/views/layouts/application.html.haml
- app/views/shared/_content_header.html.haml
- app/views/tests/index.html.haml
#What
Header下にメンズ、レディース、キッズを切り替えるためのcontent_headerを追加した。
#Why
必須のため
> content header viewを作成

- app/assets/javascripts/popup.js
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/shared/_mixin.scss
- app/views/shared/_header.html.haml
#what
・ヘッダーにポップアップ機能を追加
・カートアイコンとお気に入りアイコンに新着アイコンを追加
#why
必須のため
> ヘッダーにポップアップを追加

- config/environments/production.rb
> Deploy EC2

- app/assets/stylesheets/carts.scss
- app/controllers/carts_controller.rb
> カートコントローラーの作成

- app/assets/javascripts/popup.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/search.scss
- app/assets/stylesheets/shared/_common.scss
- app/assets/stylesheets/shared/_variables.scss
- app/assets/stylesheets/top.scss
- app/controllers/tests_controller.rb
- app/views/search/_color_select.html.haml
- app/views/tests/search.html.haml
- app/views/tops/_tops_left.html.haml
- app/views/tops/left/_brand_list.html.haml
- app/views/tops/left/_category_list.html.haml
- app/views/tops/left/_favorite_list.html.haml
- app/views/tops/left/_search_list.html.haml
- app/views/tops/left/_shop_list.html.haml
- config/routes.rb
> 検索結果ページの作成

- app/models/scraping_item.rb
スクレイピングソフトを修正
価格が0のアイテム（ZOZO SUIT)のpriceカラムの取得ができないため。
> スクレイピングソフトの修正

- app/controllers/shops_controller.rb
- app/views/brands/index.html.haml
- app/views/shared/_gender_tab.html.haml
- app/views/shared/_search_box.html.haml
- app/views/shared/_status_title.html.haml
- app/views/shops/index.html.haml
> ショップ一覧ページの作成

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items.scss
- app/controllers/brands_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/items_controller.rb
- app/controllers/shops_controller.rb
- app/controllers/sub_categories_controller.rb
- app/controllers/top_categories_controller.rb
- app/controllers/tops_controller.rb
- app/views/brands/show.html.haml
- app/views/carts/index.html.haml
- app/views/items/show.html.haml
- app/views/search/_shop_header.html.haml
- app/views/shared/nest/_nest_shop.html.haml
- app/views/shops/show.html.haml
- app/views/sub_categories/show.html.haml
- app/views/top_categories/show.html.haml
- app/views/tops/_item.html.haml
- app/views/tops/_tops_center.html.haml
- app/views/tops/_tops_left.html.haml
- app/views/tops/left/_brand_list.html.haml
- app/views/tops/left/_shop_list.html.haml
- config/routes.rb
・アイテムテンプレートにデータベースの値を反映した
・アイテム詳細ページの値をデータベースと連携した
ベース機能のため
> アイテムテンプレートとデータベースの連携

- app/models/scraping_category.rb
- db/migrate/20181006074457_add_image_to_sub_category.rb
- db/schema.rb
カテゴリー画像のスクレイピングを追加
カテゴリー一覧画像表示機能の追加
> カテゴリー画像のスクレイピング

- app/assets/javascripts/scroll.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/category.scss
- app/assets/stylesheets/favorite.scss
- app/assets/stylesheets/shared/_common.scss
- app/controllers/top_categories_controller.rb
- app/views/layouts/application.html.haml
- app/views/shared/_gender_tab.html.haml
- app/views/shared/nest/_nest_search.html.haml
- app/views/top_categories/index.html.haml
- app/views/tops/_tops_left.html.haml
> カテゴリー一覧ページの作成

- app/assets/stylesheets/favorite.scss
- app/assets/stylesheets/search.scss
- app/controllers/favorites_controller.rb
- app/views/favorites/_favorite_brand_icon.html.haml
- app/views/favorites/_favorite_shop_icon.html.haml
- app/views/favorites/index.html.haml
- db/migrate/20181008084338_change_favorite_shop_column.rb
- db/schema.rb
> お気に入りショップ機能の実装

- app/models/Scraping_all_item.rb
- app/views/search/_shop_header.html.haml
スクレイピングでショップロゴを取得
ショップ詳細ページでロゴを表示
基本機能のため
> スクレイピングによるショップロゴの取得

- app/assets/stylesheets/top.scss
- app/controllers/concerns/checked.rb
- app/controllers/shops_controller.rb
- app/controllers/tops_controller.rb
- app/models/shop.rb
- app/views/carts/index.html.haml
- app/views/favorites/index.html.haml
- app/views/tops/_item.html.haml
- app/views/tops/_shop_image.html.haml
- app/views/tops/_tops_center.html.haml
- db/schema.rb
以前チェックしたショップを表示する機能を追加
基本機能のため
> チェックしたショップの表示機能

- app/assets/javascripts/search.js
- app/assets/javascripts/search.json.jbuilder
- app/assets/stylesheets/content_header.scss
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/top.scss
- app/controllers/searches_controller.rb
- app/views/searches/index.json.jbuilder
- app/views/shared/_header.html.haml
- config/routes.rb
What
インクリメンタルサーチ実装
Why
商品、ブランド、ショップ、カテゴリから検索できるようにするため
> インクリメンタルサーチの実装

- app/assets/javascripts/pre_order.js
- app/assets/stylesheets/select.scss
- app/controllers/pre_orders_controller.rb
- app/models/delivery.rb
- app/models/payment.rb
- app/models/pre_order.rb
- app/models/user.rb
- app/views/orders/select.html.haml
- app/views/pre_orders/_next_btn.html.haml
- app/views/pre_orders/_payment.html.haml
- app/views/pre_orders/new.html.haml
- app/views/tops/_tops_center.html.haml
- config/routes.rb
- db/migrate/20181010031500_create_pre_orders.rb
- db/migrate/20181010033536_change_delivery_table.rb
- db/migrate/20181010093531_change_delivery_column.rb
- db/migrate/20181010093908_delete_type_column.rb
- db/schema.rb
> 配送、注文情報入力ページ

- app/views/orders/new.html.haml
> クレジットカードの記述削除

- config/unicorn.rb
unicorn.rbの設定
デプロイ環境のrebuildのため
> 手作業によるデプロイ設定

- app/controllers/scrapings_controller.rb
- config/routes.rb
本番環境でスクレイピングによるデータベース書き込みを行うソフトを作成
本番環境データベースへのアイテム情報入れ込みのため
> 本番環境用スクレイピングソフト作成

- app/assets/javascripts/coupon.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/coupon.scss
- app/assets/stylesheets/coupon_header.scss
- app/assets/stylesheets/shared/_common.scss
- app/assets/stylesheets/shared/_mixin.scss
- app/assets/stylesheets/top.scss
- app/controllers/coupons_controller.rb
- app/controllers/tops_controller.rb
- app/helpers/coupons_helper.rb
- app/models/item.rb
- app/views/coupons/index.html.haml
- app/views/coupons/new.html.haml
- app/views/layouts/application.html.haml
- app/views/search/_search_header.html.haml
- app/views/shared/nest/_nest_search.html.haml
- app/views/tops/_coupon_header.html.haml
- app/views/tops/_item.html.haml
- app/views/tops/_tops_center.html.haml
- app/views/tops/center/_coupon.html.haml
- app/views/tops/index.html.haml
- config/routes.rb
クーポン機能を追加
・クーポン設定ページからクーポンを適用する金額とショップを選択
・選択されたショップのアイテムがクーポン適用対象になる
・トップページ最上段にクーポンのナビゲーションバーを表示
コンテンツ充実のため
> クーポン機能の追加#1

- app/assets/javascripts/coupon.js
- app/assets/javascripts/point.js
- app/assets/stylesheets/items.scss
- app/assets/stylesheets/orders.scss
- app/controllers/coupons_controller.rb
- app/controllers/items_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/tops_controller.rb
- app/models/coupon.rb
- app/models/item.rb
- app/models/order.rb
- app/models/scraping_item.rb
- app/models/shop.rb
- app/views/items/show.html.haml
- app/views/orders/new.html.haml
- app/views/orders/show.html.haml
- app/views/tops/_coupon_header.html.haml
- app/views/tops/_tops_center.html.haml
- app/views/tops/index.html.haml
- db/migrate/20181015050042_add_shop_id_to_coupon.rb
- db/migrate/20181015092328_change_orders_table_column.rb
- db/migrate/20181015101435_delete_coupon_id_column.rb
- db/schema.rb
クーポン機能を追加した
・注文処理におけるクーポンの金額分の減算処理
・注文処理におけるクーポンの表示
コンテンツ充実のため
> クーポン機能の追加#2

- app/controllers/carts_controller.rb
- config/routes.rb
サインアップ後にカートが登録できないエラーを解消した
不具合改修
> サインアップ後にカートが登録できない不具合を解消

- app/assets/javascripts/search.js
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/search.scss
- app/controllers/searches_controller.rb
- app/views/searches/result.html.haml
- config/routes.rb
インクリメンタルサーチの修正
・検索欄が空欄の時にサーチのポップアップを消去する処理を追加
・サーチのキーワードにリンクを接続
・検索結果表示ページの作成
・検索結果の表示
UX向上
> インクリメンタルサーチの修正

- app/assets/javascripts/count_up.js
- app/assets/stylesheets/search.scss
- app/assets/stylesheets/top.scss
- app/views/carts/index.html.haml
- app/views/layouts/application.html.haml
- app/views/search/_count.html.haml
- app/views/tops/_item.html.haml
- app/views/tops/_shop_image.html.haml
- app/views/tops/_tops_center.html.haml
・検索画面でヒットした件数表示のカウントアップ機能を追加
・リンク先が存在するアイテムの画像にhoverを追加した
・トップページで消えていたクーポンタグを復活
UX向上および不具合改修
> 検索件数のカウントアップ処理追加
